/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.Add_user_Controller;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Madhavi
 */


public class Add_user extends javax.swing.JFrame {

    private ResultSet rs;
    private int userid;

    /**
     * Creates new form Add_user
     */
    public Add_user() {
        initComponents();
       // resize();
       scale_image();
        Loadadduser();//
        Fetch();
        
           Toolkit toolkit=getToolkit();
      Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }
    public void scale_image(){
    ImageIcon icon1=new ImageIcon("D:\\project\\java final ead\\pestry shop management system\\src\\Images\\man.png");
    Image img =icon1.getImage();
    Image imgScale=img.getScaledInstance(jLabel6.getWidth(),jLabel6.getHeight(),Image.SCALE_SMOOTH);
   ImageIcon scaledIcon=new ImageIcon(imgScale);
    jLabel6.setIcon(scaledIcon);

}
public void resize(){
this.setResizable(false);
        this.setAlwaysOnTop(true);
         Toolkit toolkit=getToolkit();
         int xsize=(int)toolkit.getScreenSize().getWidth();
          int ysize=(int)toolkit.getScreenSize().getHeight();
          Insets scnMax=Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
          int taskBarSize=scnMax.bottom;
          this.setSize(xsize,ysize-taskBarSize);

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_left1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_home1 = new javax.swing.JButton();
        btn_suppliar1 = new javax.swing.JButton();
        btn_product1 = new javax.swing.JButton();
        btn_adduser1 = new javax.swing.JButton();
        btn_logout1 = new javax.swing.JButton();
        jPanel_users = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_adduser = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_userid = new javax.swing.JTextField();
        btn_delete_user = new javax.swing.JButton();
        btn_update_user = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_username_add = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_password_add = new javax.swing.JTextField();
        cmb_role = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_add_user = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_report = new javax.swing.JButton();

        setUndecorated(true);

        jPanel_left1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setBackground(new java.awt.Color(0, 51, 255));

        jLabel15.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pestry Shop");

        btn_home1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_home1.setText("Home");
        btn_home1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn_home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home1ActionPerformed(evt);
            }
        });

        btn_suppliar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_suppliar1.setText("Suppliar");
        btn_suppliar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn_suppliar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suppliar1ActionPerformed(evt);
            }
        });

        btn_product1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_product1.setText("Product");
        btn_product1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn_product1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_product1ActionPerformed(evt);
            }
        });

        btn_adduser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_adduser1.setText("Add User");
        btn_adduser1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn_adduser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adduser1ActionPerformed(evt);
            }
        });

        btn_logout1.setBackground(new java.awt.Color(102, 153, 255));
        btn_logout1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logout1.setText("Log Out");
        btn_logout1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn_logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logout1ActionPerformed(evt);
            }
        });

        jPanel_users.setBackground(new java.awt.Color(204, 204, 204));

        tbl_adduser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Id", "User Name", "Password", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_adduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_adduserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_adduser);

        jPanel3.setBackground(new java.awt.Color(193, 193, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)); // NOI18N
        jPanel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("User Id");

        txt_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_useridActionPerformed(evt);
            }
        });

        btn_delete_user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_delete_user.setText("DELETE");
        btn_delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_userActionPerformed(evt);
            }
        });

        btn_update_user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update_user.setText("UPDATE");
        btn_update_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_userActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btn_delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_update_user, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update_user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(193, 193, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("User Name");

        txt_password_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password_addActionPerformed(evt);
            }
        });

        cmb_role.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Cashior" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Role");

        btn_add_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add_user.setText("ADD");
        btn_add_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_userMouseClicked(evt);
            }
        });
        btn_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_username_add, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_password_add, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btn_add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_password_add, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username_add, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("ADD USER");

        javax.swing.GroupLayout jPanel_usersLayout = new javax.swing.GroupLayout(jPanel_users);
        jPanel_users.setLayout(jPanel_usersLayout);
        jPanel_usersLayout.setHorizontalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usersLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_usersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
        );
        jPanel_usersLayout.setVerticalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btn_report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_report.setText("Reports");
        btn_report.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_left1Layout = new javax.swing.GroupLayout(jPanel_left1);
        jPanel_left1.setLayout(jPanel_left1Layout);
        jPanel_left1Layout.setHorizontalGroup(
            jPanel_left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_left1Layout.createSequentialGroup()
                .addGroup(jPanel_left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_left1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_left1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel15))
                    .addGroup(jPanel_left1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_left1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_adduser1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_left1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_product1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_left1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_suppliar1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_left1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_logout1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_left1Layout.setVerticalGroup(
            jPanel_left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_left1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_adduser1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_product1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_suppliar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_report, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel_left1Layout.createSequentialGroup()
                .addComponent(jPanel_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_left1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_left1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_userActionPerformed
        // TODO add your handling code here:
        // int userid=Integer.valueOf(txt_userid.getText());userid,
        String username=txt_username_add.getText();
        String password=txt_password_add.getText();
        String role=(String)cmb_role.getSelectedItem();
        try {
            Add_user_Controller c1=new Add_user_Controller();
            c1.adduserinput( username, password, role);
            System.out.println("1 veiw complete");
            Fetch();
            
            //             JOptionPane.showMessageDialog(null,"succesful");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());

        }
    }//GEN-LAST:event_btn_add_userActionPerformed
public void clear(){
    txt_userid  .setText("");
               txt_username_add.setText("");
                 txt_password_add.setText("");
                 cmb_role.setSelectedItem("Select");

}
    private void btn_add_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_userMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_userMouseClicked

    private void btn_update_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_userActionPerformed
        // TODO add your handling code here:
        //       int userid=Integer.valueOf(txt_userid.getText());
        //   String username=txt_username_add.getText();
        //   String password=txt_password_add.getText();
        //   String role=(String)cmb_role.getSelectedItem();
        //        try {
            //             Add_user_Controller c1=new Add_user_Controller();
            //             c1.adduserupdate( userid,username, password, role);
            //             System.out.println("1 veiw complete");
            //             Fetch();
            ////             JOptionPane.showMessageDialog(null,"succesful");
            //        } catch (Exception e) {
            //                         JOptionPane.showMessageDialog(null,e.getMessage());
            //
            //        }
             
        try {
            Connection con=DataLayer.DBconnection.getConnection();
            PreparedStatement pst;
            String q="Update tbl_adduser set  user_name= '"+ txt_username_add.getText()+"', password = '"+txt_password_add.getText() +"', role = '"+cmb_role.getSelectedItem() +"' where user_id = '"+ txt_userid.getText() +"'";
            pst=con.prepareStatement(q);
             String userid=txt_userid.getText();
                 String username=txt_username_add.getText();
        String password=txt_password_add.getText();
        String role=(String)cmb_role.getSelectedItem();
            if(userid.equals("")){
               JOptionPane.showMessageDialog(null, "Please enter user id");
           } else  if(username.equals("")){
               JOptionPane.showMessageDialog(null, "Please enter user name ");
           }
            else  if(password.equals("")){
               JOptionPane.showMessageDialog(null, "Please enter password");
           }
              else  if(role.equals("Select")){
               JOptionPane.showMessageDialog(null, "Please enter role");
           }
              else{
            pst.execute();
            JOptionPane.showMessageDialog(null, "Succesfully Updated");
            Fetch();
               clear();}
        } catch (Exception e) {   JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_update_userActionPerformed

    private void btn_delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_userActionPerformed
        // TODO add your handling code here:
        //     String userid=txt_userid.getText();
        try {Connection con=DataLayer.DBconnection.getConnection();
            String q="Delete from tbl_adduser where user_id = '"+ txt_userid.getText() +"'";
            PreparedStatement pst=con.prepareStatement(q);
            String userid=txt_userid.getText();
            if(userid.equals("")){
               JOptionPane.showMessageDialog(null, "Please enter user id");
           }
            else{
            pst.execute();
             JOptionPane.showMessageDialog(null, "Succesfully Deleted");
            Fetch();
             clear();
            }
        } catch (Exception e) {JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_btn_delete_userActionPerformed

    private void txt_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_useridActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_useridActionPerformed

    private void tbl_adduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_adduserMouseClicked
        // TODO add your handling code here:
        try {       Connection con=DataLayer.DBconnection.getConnection();
            //            int row =tbl_adduser.getSelectedRow();
            //            String tblclick=(tbl_adduser.getModel().getValueAt(row, 0).toString());
            //            String sql="select *from tbl_adduser where user_id='"+tblclick+"'";
            //          PreparedStatement pst=con.prepareStatement(sql);
            //            if (rs.next()) {
                //
                //                txt_userid.setText(rs.getString("user_id").toString());
                //
                //                txt_username_add.setText(rs.getString("user_name"));
                //
                //                txt_password_add.setText(rs.getString("password"));
                //
                //                cmb_role.setSelectedItem(rs.getString("role"));
                //            }
            // get the model from the jtable
            DefaultTableModel model = (DefaultTableModel)tbl_adduser.getModel();

            // get the selected row index
            int selectedRowIndex =tbl_adduser.getSelectedRow();

            // set the selected row data into jtextfields
            txt_userid.setText(model.getValueAt(selectedRowIndex, 0).toString());
            txt_username_add.setText(model.getValueAt(selectedRowIndex, 1).toString());
            txt_password_add.setText(model.getValueAt(selectedRowIndex, 2).toString());
            cmb_role.setSelectedItem(model.getValueAt(selectedRowIndex, 3).toString());
            //        DefaultTableModel tblmodel=(DefaultTableModel)tbl_adduser.getModel();
            //        int userid=(int) tblmodel.getValueAt(tbl_adduser.getSelectedRow(),0);
            //        String username=tblmodel.getValueAt(tbl_adduser.getSelectedRow(),1).toString();
            //          String password=tblmodel.getValueAt(tbl_adduser.getSelectedRow(),2).toString();
            //            String role=tblmodel.getValueAt(tbl_adduser.getSelectedRow(),3).toString();
            //
            //         txt_username_add.setText(username);
            //         txt_password_add.setText(password);
            //         cmb_role.setSelectedItem(role);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tbl_adduserMouseClicked

    private void btn_home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home1ActionPerformed
        // TODO add your handling code here:
           setVisible(false);
        new Dashbord().setVisible(true);
    }//GEN-LAST:event_btn_home1ActionPerformed

    private void btn_adduser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adduser1ActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        new Add_user().setVisible(true);
    }//GEN-LAST:event_btn_adduser1ActionPerformed

    private void btn_product1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_product1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Product().setVisible(true);
    }//GEN-LAST:event_btn_product1ActionPerformed

    private void btn_suppliar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suppliar1ActionPerformed
 setVisible(false);
        new Suppliar().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_suppliar1ActionPerformed

    private void btn_logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logout1ActionPerformed
 setVisible(false);
        new Login().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logout1ActionPerformed

    private void txt_password_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password_addActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Report().setVisible(true); 
    }//GEN-LAST:event_btn_reportActionPerformed
 public void serchbox(){
//     try {
//         
//    
//     Connection con=DataLayer.DBconnection.getConnection(); 
//     PreparedStatement pst=con.prepareStatement("select * from tbl_adduser where user_id='"+txt_userid.getText()   +"'");
//     ResultSet rs=pst.executeQuery();
//     while (rs.next()) {
//         int userid=rs.getInt("user_id");
//     
//                String username = rs.getString("user_name");
//                String password = rs.getString("password");
//                String role = rs.getString("role");
//          
//     } } catch (Exception e) {
//          JOptionPane.showMessageDialog(null,e.getMessage());
//     }
 
 }
    public void autoid(){
//     try {
//          Connection con=DataLayer.DBconnection.getConnection(); 
//          Statement st=con.createStatement();
//          ResultSet rs=st.executeQuery("select Max(user_id) from tbl_adduser");
//          rs.next();
//          rs.getString("Max(user_id)");
//          if (rs.getString("Max(user_id)")==null) {
//             txt_userid.setText({"U001");
//             
//          }
//             else{
//                    Long userid=Long.perseLong(rs.getString("Max(user_id)").su)
//                     }
//         }
//          
//          
//     } catch (Exception e) {
//     }
 
    
      
 }
    public void Loadadduser(){
//     try {
////             Connection con=DataLayer.DBconnection.getConnection(); 
////  String sql="select *from tbl_adduser";
////          PreparedStatement pst=con.prepareStatement(sql);
////            rs=pst.executeQuery();
////            while (rs.next()) {
////             
//             
//         }
//     } catch (Exception e) {
//     }
    
 }
 private void Fetch(){
     try {
          int q;
      Connection con=DataLayer.DBconnection.getConnection(); 
  String sql="select *from tbl_adduser";
          PreparedStatement pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            ResultSetMetaData rss=rs.getMetaData();
            q=rss.getColumnCount();
            DefaultTableModel df=(DefaultTableModel)tbl_adduser.getModel();
            df.setRowCount(0);
            
            while (rs.next()) {
            Vector v2=new Vector();
                for (int i = 0; i < 10; i++) {
                    v2.add(rs.getString("user_id"));
                    v2.add(rs.getString("user_name"));
                    v2.add(rs.getString("password"));
                    v2.add(rs.getString("role"));
                }
            df.addRow(v2);
            }
     } catch (Exception e) {
     }
    
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_user;
    private javax.swing.JButton btn_adduser1;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete_user;
    private javax.swing.JButton btn_home1;
    private javax.swing.JButton btn_logout1;
    private javax.swing.JButton btn_product1;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_suppliar1;
    private javax.swing.JButton btn_update_user;
    private javax.swing.JComboBox<String> cmb_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_left1;
    private javax.swing.JPanel jPanel_users;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_adduser;
    private javax.swing.JTextField txt_password_add;
    private javax.swing.JTextField txt_userid;
    private javax.swing.JTextField txt_username_add;
    // End of variables declaration//GEN-END:variables
}
