/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Model.DBconnection.con;
import View.Dashbord;
import View.Login;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Madhavi
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        scale_image();
         Toolkit toolkit=getToolkit();
      Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_product_report = new javax.swing.JButton();
        btn_user_report = new javax.swing.JButton();
        btn_supp_report = new javax.swing.JButton();
        btn_bill_report = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_left.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));

        btn_logout.setBackground(new java.awt.Color(102, 153, 255));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logout.setText("Log Out");
        btn_logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Report");

        btn_product_report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_product_report.setText("Product Details");
        btn_product_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_product_reportActionPerformed(evt);
            }
        });

        btn_user_report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_user_report.setText("User Details");
        btn_user_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_reportActionPerformed(evt);
            }
        });

        btn_supp_report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_supp_report.setText("Suppliar Details");
        btn_supp_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supp_reportActionPerformed(evt);
            }
        });

        btn_bill_report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_bill_report.setText("Bill Details");
        btn_bill_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bill_reportActionPerformed(evt);
            }
        });

        btn_home.setBackground(new java.awt.Color(102, 153, 255));
        btn_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_home.setText("Home");
        btn_home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_leftLayout = new javax.swing.GroupLayout(jPanel_left);
        jPanel_left.setLayout(jPanel_leftLayout);
        jPanel_leftLayout.setHorizontalGroup(
            jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_leftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(140, 140, 140))
                    .addGroup(jPanel_leftLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_user_report, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_product_report, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_supp_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_bill_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        jPanel_leftLayout.setVerticalGroup(
            jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_leftLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_product_report, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_supp_report, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_user_report, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bill_report, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(jPanel_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_left, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void scale_image(){
    ImageIcon icon=new ImageIcon("D:\\project\\java final ead\\pestry shop management system\\src\\Images\\pexels-ketut-subiyanto-4559555.jpg");
    Image img =icon.getImage();
    Image imgScale=img.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
   ImageIcon scaledIcon=new ImageIcon(imgScale);
    jLabel1.setIcon(scaledIcon);
   
}
    private void btn_product_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_product_reportActionPerformed
        // TODO add your handling code here:
//        try {
            Connection con=DataLayer.DBconnection.getConnection();
String path="D:\\\\project\\\\java final ead\\\\pestry shop management system\\\\src\\\\Report\\\\report1.jrxml";
                JasperReport jr = null;
        try {        
            jr = JasperCompileManager.compileReport(path);
       
                JasperPrint  jp = JasperFillManager.fillReport(jr,null,con);
                JasperViewer.viewReport(jp,false);
} catch (Exception e) 
{
            JOptionPane.showMessageDialog(null, "error "+e);
}  
       
//        Connection con=DataLayer.DBconnection.getConnection();
//         JasperDesign jdesign =JRXmlLoader.load("D:\\project\\java final ead\\pestry shop management system\\src\\Report\\report1.jrxml");
//        String sql="select *from tbl_product";
//        JRDesignQuery updateQuary=new JRDesignQuery();
//        updateQuary.setText(sql);
//        jdesign.setQuery(updateQuary);
//        JasperReport jreport=JasperCompileManager.compileReport(jdesign);
//        JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con);
//            JasperViewer.viewReport(jprint);
//        } catch (Exception e) {
//        }
         
         
    }//GEN-LAST:event_btn_product_reportActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_user_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_reportActionPerformed
        // TODO add your handling code here:
         Connection con=DataLayer.DBconnection.getConnection();
String path="D:\\project\\java final ead\\pestry shop management system\\src\\Report\\user.jrxml";
                JasperReport jr = null;
        try {        
            jr = JasperCompileManager.compileReport(path);
       
                JasperPrint  jp = JasperFillManager.fillReport(jr,null,con);
                JasperViewer.viewReport(jp,false);
} catch (Exception e) 
{
            JOptionPane.showMessageDialog(null, "error "+e);
}  
//            try {    Connection con=DataLayer.DBconnection.getConnection();
//String path="D:\\project\\java final ead\\pestry shop management system\\src\\Report\\Adduser.jrxml";
//                JasperReport jr = null;
//         
//            jr = JasperCompileManager.compileReport(path);
//       
//                JasperPrint  jp = JasperFillManager.fillReport(jr,null,con);
//                JasperViewer.viewReport(jp,false);
//} catch (Exception e) 
//{
//            JOptionPane.showMessageDialog(null, "error "+e);
////}  
//try{
//  Connection con=DataLayer.DBconnection.getConnection();
//         JasperDesign jdesign =JRXmlLoader.load("D:\\\\project\\\\java final ead\\\\pestry shop management system\\\\src\\\\Report\\\\Adduser.jrxml");
//        String sql="select *from tbl";
//        JRDesignQuery updateQuary=new JRDesignQuery();
//        updateQuary.setText(sql);
//        jdesign.setQuery(updateQuary);
//        JasperReport jreport=JasperCompileManager.compileReport(jdesign);
//        JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con);
//            JasperViewer.viewReport(jprint);
//        } catch (Exception e) {
//        }
        
    }//GEN-LAST:event_btn_user_reportActionPerformed

    private void btn_supp_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supp_reportActionPerformed
        // TODO add your handling code here:
         Connection con=DataLayer.DBconnection.getConnection();
String path="D:\\project\\java final ead\\pestry shop management system\\src\\Report\\suppliar.jrxml";
                JasperReport jr = null;
        try {        
            jr = JasperCompileManager.compileReport(path);
       
                JasperPrint  jp = JasperFillManager.fillReport(jr,null,con);
                JasperViewer.viewReport(jp,false);
} catch (Exception e) 
{
            JOptionPane.showMessageDialog(null, "error "+e);
}  
       
    }//GEN-LAST:event_btn_supp_reportActionPerformed

    private void btn_bill_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bill_reportActionPerformed
        // TODO add your handling code here:
         Connection con=DataLayer.DBconnection.getConnection();
String path="D:\\project\\java final ead\\pestry shop management system\\src\\Report\\Bill.jrxml";
                JasperReport jr = null;
        try {        
            jr = JasperCompileManager.compileReport(path);
       
                JasperPrint  jp = JasperFillManager.fillReport(jr,null,con);
                JasperViewer.viewReport(jp,false);
} catch (Exception e) 
{
            JOptionPane.showMessageDialog(null, "error "+e);
}  
        
    }//GEN-LAST:event_btn_bill_reportActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
             setVisible(false);
        new Dashbord().setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bill_report;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_product_report;
    private javax.swing.JButton btn_supp_report;
    private javax.swing.JButton btn_user_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel_left;
    // End of variables declaration//GEN-END:variables
}
